### ISSUE TITLE
Application of default I/E rule

### ISSUE THREAD

**Issue by olejandro** [kanors-emr/Veda2.0-Installation#12]
TIMES and Veda Attributes no longer shows whether there is a default I/E rule applied.

**Comment by akanudia** [comment]
you are right. Some of those were not correct, and far more accurate information is available in the table below in any case. We will fix this at some point in the future.

**Comment by olejandro** [comment]
Seems the table did not get through...

**Comment by akanudia** [comment]
I meant the table with details - at the bottom of the Attribute master form.
