### ISSUE TITLE
update excel function failed (2.16.1.1)

### ISSUE THREAD

**Issue by ZhangShuTHU** [kanors-emr/Veda2.0-Installation#13]
I just tried updating from 2.15 to 2.16 and everything was working fine before. In the 2.16 version, after clicking to update excel, it freezes for about ten seconds, but it does not enter the automatic program of updating the form.

**Comment by ravindersinghchauhan** [comment]
Please verify whether any recent error log files have been generated in the logs folder of VEDA. Kindly share the error log and provide a screenshot of the specific issue, particularly the point where the application freezes.

**Comment by ZhangShuTHU** [comment]
I didn't see useful information in the veda error list.



Name : Veda.Common.KanLogger {2.16.1.1}
 Time : 2023-07-26 19:50:37.4828
 Type : TRACE
 Machine / User : ZHANGSHU-LAB / ZHANGSHU-LAB\44728
 StackTrace :  Program.Main
 Message : Windows information logging.
 

 --------------------------------------------------------
 Name : Veda.Common.KanLogger {2.16.1.1}
 Time : 2023-07-26 19:51:06.1234
 Type : TRACE
 Machine / User : ZHANGSHU-LAB / ZHANGSHU-LAB\44728
 StackTrace :  Program.Main
 Message : Windows information logging.
 

 --------------------------------------------------------
 Name : Veda.Common.KanLogger {2.16.1.1}
 Time : 2023-07-26 20:17:40.3443
 Type : TRACE
 Machine / User : ZHANGSHU-LAB / ZHANGSHU-LAB\44728
 StackTrace :  Program.Main
 Message : Windows information logging.

**Comment by ZhangShuTHU** [comment]
I found this to be an occasional problem, and I tried 4 times in a row, and on the fourth time, I managed to activate the automatic update program

**Comment by ravindersinghchauhan** [comment]
I have confirmed that this functionality is functioning properly(in 2.16.1.1) with small tables (row counts > 2500). However, with larger tables (row counts < 2500), it may take more time to process and update the files. Please be patient when dealing with larger tables.

I recommend trying this feature with a smaller table to see if the issue still persists. If you encounter any further problems, please let us know.

**Comment by ZhangShuTHU** [comment]
Thanks! Windows 11 today's automatic update is the culprit, I rolled back the update and everything is working fine

**Comment by ravindersinghchauhan** [comment]
Great! Thanks for the update.
