### ISSUE TITLE
Items Detail panel error

### ISSUE THREAD

**Issue by panosev** [kanors-emr/Veda2.0-Installation#15]
Hi Amit and team, 
In the Items Detail panel, when I selected a process to view its data and by chance in the data grid, I right-clicked and select re-load data (I did this on top of the field Aggregates in the data grid), I got the message "Unable to cast object of type 'Telerik.Pivot.Core.DoubleGroupDescription' to type 'Telerik.Pivot.Core.PropertyGroupDescription'". Since then, even if I close VEDA and start the model synchronisation from scratch or delete the user settings and model AppData, I am not able to browse the data in any process in the Items Detail panel. I am using VEDA version 2.17.1.1. However, this error is specific to the model in which I did the action. The rest of the models in my VEDA database do not have this issue. I will try to re-install everything later today and let you know if, with the re-installation of VEDA and re-synchronisation of all my models, this issue has gone. 
Maybe you can tackle this in one of the next releases. 
![Capture](https://github.com/kanors-emr/Veda2.0-Installation/assets/58793267/b4c51325-2904-4504-9372-b5408dc83ec8)

Best regards, 
Vangelis

**Comment by panosev** [comment]
UPDATE: by completely deleting the model from the VEDA database and re-importing the model EXCEL files into the database, the issue disappeared without needing to re-install VEDA. 
It is interesting that the SYNC from scratch alone did not solve the issue, as long as the SYNC was performed on the "damaged" version.

**Comment by akanudia** [comment]
Thanks for pointing this out Vangelis. We will try to track this down.
