### ISSUE TITLE
Mapping of COST

### ISSUE THREAD

**Issue by olejandro** [kanors-emr/Veda2.0-Installation#16]
Currently TIMES and Veda Attributes indicates `COST` as an alias for `IRE_PRICE`. The old Veda used to also map `COST` to `ACT_COST` for non `IRE` processes. Would be good to add this info to TIMES and Veda Attributes if this behaviour is also present in Veda 2.
@akanudia

**Comment by akanudia** [comment]
sorry for the delayed response. This behavior is not present in Veda2. I have added this to the "things that are different" section of Veda doc.

**Comment by olejandro** [comment]
Ok, thanks a lot @akanudia !
