### ISSUE TITLE
Check Groups pending saving?

### ISSUE THREAD

**Issue by Antti-L** [kanors-emr/Veda2.0-Installation#17]
VEDA seems to know that e.g. a scenario group has been edited but not yet saved, by showing the "`Roundabout`" icon.
Would it be possible to warn the user when launching run(s) in the situation where VEDA can see that some of the groups referred to in the run(s) has been **edited but not yet saved**?   Something like "Scenario group has not been saved, are you sure to continue?" `OK/Cancel`.

I have several times wasted time due to noticing only later that I had forgotten to save my edits to the Scenario group, or the Properties group.  Apologies if this check has already been implemented.

**Comment by akanudia** [comment]
That's a good idea, we will put this on our list.

**Comment by akanudia** [comment]
Implemented in version 3.0.1.0
