### ISSUE TITLE
Strange scen panel in Results tab

### ISSUE THREAD

**Issue by panosev** [kanors-emr/Veda2.0-Installation#19]
Dear VEDA 2.0 Team,
I am using the VEDA 2.18.1.1 version, and I noticed in the result tab the following panel. These scen items were not created by me. What are these?
![image](https://github.com/kanors-emr/Veda2.0-Installation/assets/58793267/6a123cb9-79d1-4b59-b6d4-704ec46d9dd6)

**Comment by akanudia** [comment]
When you use parametric scenarios facility, you end up with scenario names like <case>~000#. ~ScenMap table in the report definitions file generates understandable scenario names, like the ones you have. This creates a new dimension "Scen", which was done only for Reports so far. This dimension has started going to Results too. Looks like you are using the Reports feature but but not parametric scenarios.

We can suppress this dimension if the Scenmap table is missing or empty in report definitions file.

And I am curious - how did you create these cases.. via some GAMS programming tricks?

**Comment by panosev** [comment]
Hi Amit, Thanks a lot for the clarification. Apparently, these scenarios were introduced in the ~ScenMap table in the report definitions. I was not aware that I was using the Reports feature, until I saw the file LMADefs-EU_TIMES.xls (I am working these days with the JRC EU TIMES), in the model directory, so probably one of the previous users of the model introduced them there. So, no GAMS programming tricks :-)

**Comment by panosev** [comment]
Issue can be closed now :-)
