### ISSUE TITLE
UC constraints on trade processes seems not to appear in the Item Details RES Process View

### ISSUE THREAD

**Issue by panosev** [kanors-emr/Veda2.0-Installation#20]
Dear Team, 

I have noticed that the UC constraints do not appear on the top left of the RES graph in Item Details when selecting the process view. 
Maybe you want to tackle this in a future version of VEDA. 

Keep up the good work :-)

![image](https://github.com/kanors-emr/Veda2.0-Installation/assets/58793267/b980191a-d835-496a-88b3-a06e0e7fc2ce)

**Comment by akanudia** [comment]
Thanks for flagging this - I have also noticed this but didn't bother addressing it yet.

**Comment by rohitkanors** [comment]
Fixed in Veda2.0 version 2.020.1.1
