### ISSUE TITLE
Files are skipped during sync

### ISSUE THREAD

**Issue by olejandro** [kanors-emr/Veda2.0-Installation#22]
Seems that from version 2.18 Veda skips some files during synchronisation. An attemp to select and synchronise the omitted files results in:

```
StackTrace : The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER)) ExecutionContext.RunInternal => <HandleFillTagExcelWriting>d__19.MoveNext => SyncControllerUiWork.HandleExceptionInTagProcessing
 Message : System.Runtime.InteropServices.COMException (0x8001010A): The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER))
   at Microsoft.Office.Interop.Excel._Worksheet.set_EnableCalculation(Boolean RHS)
   at Veda.FrontEnd.SyncController.TagsProcessingFramework.TagsClasses.FillTagWrapper.<HandleFillTagExcelWriting>d__19.MoveNext()
```

**Comment by olejandro** [comment]
This is the model I've observed the error on: https://github.com/esma-cgep/tim

**Comment by kanors-himanshu03** [comment]
Hi,
We are looking into this but in our preliminary testing we could not reproduce the same error using the latest localhost and the model that you provided. Are you facing this problem consistently?

Also, this kind of error generally originates from excel. So please make sure that there are no lingering excel processes in the background from your task manager or some kind of popups in excel that require user attention before moving forward.

**Comment by olejandro** [comment]
Thanks @kanors-himanshu03! It ia a new system; I have not experienced this before. I had normally used an installed version, but this time decided to go for localhost.
I have now tried it with version 2.14 - 2.20 each time after a restart. Each time files are skipped; no excel dialogues or prompts in sight. 
Here is how the Navigator window looks after a full sync:
![image](https://github.com/kanors-emr/Veda2.0-Installation/assets/25687793/fe097c3e-7a1d-492e-a118-c6cf906e68b5)

**Comment by olejandro** [comment]
I've now also installed an installer version of Veda (2.20). I get the following error:

![image](https://github.com/kanors-emr/Veda2.0-Installation/assets/25687793/3a731074-80b1-40d3-945a-1895010f83b9)

There is nothing in the error log about this...

**Comment by ravindersinghchauhan** [comment]
Hello Olex,

Can we arrange a remote desktop meeting to address the issue?

**Comment by olejandro** [comment]
Hi @ravindersinghchauhan, yes, thanks! I'll get in touch with you to find a time.
Meanwhile, I can confirm that Veda 2.20 syncs fine with another large model, as well as with Demo 12.

**Comment by ravindersinghchauhan** [comment]
Hi @olejandro,
Thanks for letting us know that other models are working fine on your machine with the VEDA 2.20 version.
Send me an email whenever you are available for a meeting.

**Comment by olejandro** [comment]
@ravindersinghchauhan this beta version seems to work well: https://www.dropbox.com/scl/fi/ophz6ytetpr0fvgq7mc8a/Veda2.0_localhost_2.19.2.4.7z?rlkey=6f9ybb2vlbtd9rai6ex288z0t&dl=0

**Comment by ravindersinghchauhan** [comment]
@olejandro great!
Thank you for the update.

**Comment by olejandro** [comment]
@ravindersinghchauhan could you please let me know when the changes in the beta make it to the main versions?

**Comment by ravindersinghchauhan** [comment]
Dear @Olejandro, We are on the verge of launching the next major version.

**Comment by olejandro** [comment]
Ok, thanks!
