### ISSUE TITLE
Scroll bar not always visible in the Items Detail panel

### ISSUE THREAD

**Issue by panosev** [kanors-emr/Veda2.0-Installation#24]
Dear VEDA Team, 

A minor issue: 
Sometimes the horizontal scroll bar in the data view grid is not available when looking at the Items Detail and the VEDA window is not maximised. 
It becomes visible only when I re-size the window. 
I am using VEDA 3.0.1.0 but this was also present in the previous versions of VEDA 2
![Capture](https://github.com/kanors-emr/Veda2.0-Installation/assets/58793267/4f4131da-5d1a-4e1a-8325-02c7c1789f06)

Best regards, 
Vangelis

**Comment by akanudia** [comment]
Before we look for a solution, here is a workaround: the button shown below will open a layout helper on any pivot view. You can check the "Aggregated" box on top and put only the dimensions you want on rows/columns.

![pivot grid layout button](https://github.com/kanors-emr/Veda2.0-Installation/assets/50097598/0c6c7a28-d956-4268-9329-6790917a18bc)

**Comment by panosev** [comment]
Thank you Amit for the workaround. I will use it until this is fixed in one of the next releases of VEDA 2

**Comment by deepakgupta256** [comment]
The DataGrid can display vertical and horizontal scrolls within the data region only. However, it doesn't support scrolling specifically for the RowHeader area. 
As seen in the screenshot, the RowHeader occupies all available width. Therefore, the workaround suggested by @akanudia  remains the sole solution for this issue.
