### ISSUE TITLE
NCAP_AFC~ACT and NCAP_AFC~NRG not recognised in FI_T tables

### ISSUE THREAD

**Issue by olejandro** [kanors-emr/Veda2.0-Installation#25]
`NCAP_AFC~ACT` and `NCAP_AFC~NRG` does not seem to be recognised in FI_T tables. Although no error is thrown, the input is not displayed in Items Detail.

**Comment by akanudia** [comment]
Addressed in version 3.0.2.0.

**Comment by Antti-L** [comment]
@akanudia Can I ask how this was addressed?  Does VEDA now accept NRG / MAT / ENV / DEM / FIN as an Item in the `FI_T` data column headers ?  Or is an error now issued?   (And the same question about ACT).

**Comment by akanudia** [comment]
@Antti-L , NRG and ACT will be accepted as items in FI_T data col headers, and under cset_cn in TFM tables (sorry @olejandro ;) ) - basically to be interpreted as commodity_group.

Do you think it will be useful to include MAT, ENV, DEM, and FIN too?

**Comment by Antti-L** [comment]
Thanks!  Well yes, if `NRG` is accepted, I think all commodity types should likewise.  Great that `ACT` is now accepted, but it is a predefined **commodity** in TIMES, and e.g. `STG_SIFT(r,y,p,com,s)` also accepts `ACT`, and so would it work for `STG_SIFT`?

**Comment by akanudia** [comment]
Yes, it will work. Added the rest for the next release.
