### ISSUE TITLE
Import/export of case definitions between model versions

### ISSUE THREAD

**Issue by BakytzhanSuleimenov** [kanors-emr/Veda2.0-Installation#27]
Hi there,
Is it possible to import/export cases from the run manager between model versions? I would like to copy some run cases from one version of the model to another, so far I have managed to do it by copypasting between JSON files, but is there a better way through VEDA? Since it is possible to import from old VEDA, I thought that it is possible.

This is not an issue report, but a feature suggestion.

Best regards,
Bakytzhan

**Comment by ravindersinghchauhan** [comment]
Hello Bakytzhan,

Currently, in VEDA 2.0, the option to import both groups and cases simultaneously from one model to another exists. Users are not required to manually copy JSON files; instead, they simply need to indicate the app data folder of the source model where the JSON data is stored. The system will then automatically load the groups and cases accordingly. To complete the import, users only need to click the save button, transferring all groups and cases from the source model to the current one.

Please be aware: This process requires copying groups before proceeding to copy cases. Make sure that groups are copied first, then cases.

Please adhere to the following steps:

1. Navigate to the Tools menu and select 'Sync AppData folder.'
2. The SyncToolForm window will open. Click the three dots (...) button to locate the source model's 'app data folder.'
3. Once located, all data will automatically load in the Groups and Cases tabs within the Run Manager Tab. On the left side, you will see the current model's groups, while on the right side, you'll find the source model's 'groups' data, which can be copied by checking the appropriate boxes. Click 'Save' to transfer the selected data to the left side.
4. Repeat the above process for the 'Cases' data within the 'Cases' tab.
5. Close the SyncToolForm window and press F5 to view the copied cases in the Run Manager.

Should you encounter any difficulties during these steps, please inform us, and we can arrange a web meeting to address the issue.

Please be aware that this tool is currently in its beta phase. Before proceeding with the aforementioned steps, kindly create a backup of your current app data folder. 

If you have any suggestions for improvements, we encourage you to share them with us. We will consider implementing them based on user feedback.

Thanks
