### ISSUE TITLE
TOP_IRE entries not generated for processes defined as IRE in ~FI_Process table

### ISSUE THREAD

**Issue by olejandro** [kanors-emr/Veda2.0-Installation#28]
It seems that `TOP_IRE` entries are not generated for processes if they are defined as `IRE` in an ~FI_Process table. The absence of the relevant entries leads to the processes not being recognised as trade processes by TIMES.

At the same time, `PRC_MAP` does include the relevant entries.

**Comment by Antti-L** [comment]
Some background info: Olex was not able to make a UC constraint based on **`UC_IRE`** working, and approached me for an explanation.  I found out that the process referred to in UC_IRE was not a trade process (even though it was defined to be of type **`IRE`**), which explained the problem.  

I think that VEDA should either recognize **`IRE`** as a way of defining the process as a **trade process** (I guess it should be like IMP+EXP), or reject it and issue an error.  Letting it just through without actually making the process as a trade process is a source of inconsistency and may potentially cause notable confusion. I am now adding a TIMES **QA_Check** for it as well, but I think it would be good to catch under VEDA.

**Comment by akanudia** [comment]
@Antti-L, we can add TOP_IRE entries if we assume `IMPEXP` as the exogenous region. Would that be OK?

**Comment by Antti-L** [comment]
Yes, sure that would be ok, just like with IMP+EXP.  Then this TIMES process type would be supported by VEDA (the IMP and EXP types are not even known by TIMES).

**Comment by akanudia** [comment]
Done; will be available in the next update.

**Comment by Antti-L** [comment]
> available in version 3.0.4

Was that premature? I see [Revert "3.0.4.0 released"](https://github.com/kanors-emr/Veda2.0-Installation/commit/d18ab44a97e8996bb387af492953deac08879505) in the Localhost folder, and the package available there is v3.0.2, i.e. even v3.0.3 seems to have disappeared.    :crying_cat_face:

**Comment by olejandro** [comment]
Seems that both have been reverted: https://github.com/kanors-emr/Veda2.0-Installation/commits/master/

**Comment by akanudia** [comment]
Sincere apologies for the confusion. The FI_T tag QC enhancement had forced us to change some core data processing that needed more thorough testing than we did before releasing version 3.0.3. We should be able to release 3.0.5 later today, but it could also take another day.

At this time, 3.0.2 is the last stable version.

**Comment by akanudia** [comment]
Version 3.0.5 has been released.
