### ISSUE TITLE
Solving a case with multiple timeslice definitions selected

### ISSUE THREAD

**Issue by olejandro** [kanors-emr/Veda2.0-Installation#29]
When a attempting to solve a case with multiple timeslice definitions selected (by accident), I've observed the following behaviour from Veda:
- no error is thrown;
- only "> Start" and "> Completed" lines are output to the log window;
- no dd files are written.

I think it is reasonable, that the no attempt is made to solve the model when multiple timeslice definitions are selected in a scenario group. It would be very helpful to warn the user about it though.

**Comment by olejandro** [comment]
Alternatively, one could use the scenario order to overwrite one definition with another and attempt to solve the model anyway...

**Comment by deepakgupta256** [comment]
We attempted to solve a case with Scenario group having TimeSlice definition in two Regular Scenarios and got the following detailed error message popup. 

Did you not receive the messages outlined below? Or is your case different from what I am currently testing?

![MultiTimeSlice1](https://github.com/kanors-emr/Veda2.0-Installation/assets/50098218/9165e6ab-e9ab-42a0-827b-63e6bfd512e6)
![MultiTimeSlice2](https://github.com/kanors-emr/Veda2.0-Installation/assets/50098218/be06438e-fdaa-43d3-a1f5-6106b72cdd99)

**Comment by olejandro** [comment]
Thanks for taking a look at it @deepakgupta256. I do not get the error message; also in my case it says "Completed" instead of "Completed with error". I use localhost version 3.0.2.

I am able to reproduce the behaviour (i.e. no error message and "Completed" instead of "Completed with error") on this [model](https://github.com/esma-cgep/tim) by adding `A_SYS_SAD_1TS` to NoMitigation group and solving No_Mitigation  case.

**Comment by akanudia** [comment]
The message was inadvertently suppressed in some cases. The non-fatal error thrown due to missing TS def in SysSettings has also been addressed in version 3.0.3.
