### ISSUE TITLE
Allow selecting/resetting the folder for GDX reference

### ISSUE THREAD

**Issue by olejandro** [kanors-emr/Veda2.0-Installation#30]
Currently creating a copy of the model folder results in gdx references pointing to the files in the original folder. There appears to be no means of changing the path other than: 

1. saving the case without a gdx reference
2. creating a new gdx reference

**Comment by Antti-L** [comment]
I concur with that.  
I would also like to have the possibility to select the GDX file from the folder where it would be copied anyway when running, if it exists there already.  In other words, currently, if I want to use a GDX file, it has to be copied to the `Appdata\GAMSSAVE` of the model template folder for it to appear for selection under VEDA.  And then, when running the case, VEDA copies it to the `GAMSSAVE` folder under the work folder.  But if the GDX file is **already there** under the work folder, why not allow to select that file, without needing to first copy it to the Appdata\GAMSSAVE and then VEDA would copy it back to the work folder?

Being able to select the desired folder for the GDX files would apparently solve both issues, but maybe one could always allow also pointing to the GDX files under the work folder (if such exist, excluding data-only files)?

**Comment by akanudia** [comment]
We have started wokring on this. Will be available in the version after 307.

**Comment by akanudia** [comment]
@olejandro, let us know what you think about what is been done in version 3.1.1.

**Comment by kanors-himanshu03** [comment]
The below documentation will help in understanding new features related to GDX file handling better.

https://veda-documentation.readthedocs.io/en/latest/pages/Run%20Manager.html#managing-gdx-files

**Comment by olejandro** [comment]
Thanks! Judging from the docs, seems very convinient and straight forward. I'll try to test it soon.
My maintenance expired about a month ago though, so probably won't work with the new version until the license is renewed?

**Comment by akanudia** [comment]
You can continue to update to any Version 3.x.x so long as your maintenance was active beyond 28Nov23.
