### ISSUE TITLE
Modification of solver option files

### ISSUE THREAD

**Issue by victor-guillot** [kanors-emr/Veda2.0-Installation#32]
Would it be possible to modify the solver opt files in the run manager. I think the gurobi.opt file is not as clear and intuitive as other cplex opt files. My suggestion would be a simple file like this one :

Method=2
Crossover=1
Threads=7

What do you think about adding a possibility to use the new highs (https://highs.dev/) solver ? Not as fast as gurobi/cplex but improving fast: https://forum.openmod.org/t/open-source-highs-solver-performance-boost-for-energy-system-models/2922 
A suggestion could be: 

solver = ipm
run_crossover = true
ipm_optimality_tolerance = 1e-6
threads = 7

**Comment by ravindersinghchauhan** [comment]
See this [video](https://github.com/kanors-emr/Veda2.0-Installation/assets/53930350/3e6bc2fb-0e88-450c-b684-e1e3cf173321).

**Comment by akanudia** [comment]
Thanks for testing with Gurobi. I don't have this solver so couldn't test the default option file that I had made - based on the GAMS website 3-4 years ago. It will be great if you can share an options file that we can use as the default one in the resources folder.

**Comment by akanudia** [comment]
HiGHS will be available in the next update.

In the meantime, you can do the following to use it:

1. Launch a normal run and cancel it.
2. Open the GAMSWrk folder where the DD and RUN files reside.
3. Edit the <casename>.RUN file and replace cplex/gurobi with highs.
4. put highs.opt in this folder.
5. Execute VTRUN.CMD to run the model

**Comment by akanudia** [comment]
looks like cplex, gurobi, and xpress have some more money to make.

**Comment by akanudia** [comment]
HiGHS available under version 3.0.5
