### ISSUE TITLE
Update Excel Function Unit Bug

### ISSUE THREAD

**Issue by ZhangShuTHU** [kanors-emr/Veda2.0-Installation#34]
Currently, I use VEDA 2 (vervion 3.0.2). When VEDA2 was not updated to the V3 major versions, "Update Excel" was able to update the data according to the **active unit**, but after I upgraded, the updated data did not take into account the **active unit**, and the output file was set up according to the model original unit. (btw The batch export function has the correct units).

Also, in both version 2 and 3 there was a situation where the **sub total** and **grand total** items could not be updated, I don't know if this can be fixed well.

**Comment by kanors-himanshu03** [comment]
Thanks for bringing it to our attention. The "Update Excel" feature to accommodate the active unit will be fixed in the next production release.

We will also look into what can be done for sub/ grand totals.

**Comment by ZhangShuTHU** [comment]
And Veda output these error information in the Log file, I think it's useful to fix bug.


 Name : Veda.Common.KanLogger {3.0.2.0}
 Time : 2024-02-22 12:44:04.6887
 Type : ERROR
 Machine / User : LAB-SERVER3 / LAB-SERVER3\ZS
 StackTrace : ??????????????? RadMenuItem.OnClick => RadElement.OnClick => UpdateExcelPresenter.Process
 Message : System.NullReferenceException: ???????????????
   ? Veda.ExcelOperations.ResultsUpdateExcelFeatureManager.GetToUnitFromExcel(Worksheet worksheet)
   ? Veda.ExcelOperations.ResultsUpdateExcelFeatureManager.GetLayoutForSingleView(String viewName, String sheetName, Workbook workbook, String absFilePath)
   ? Veda.ExcelOperations.ResultsUpdateExcelFeatureManager.GetExistingLayoutForAllViews(Dictionary`2 readBatchExportedFileAndGetViewNames, Workbook workbook, String absFilePath)
   ? Veda.ExcelOperations.ResultsUpdateExcelFeatureManager.GetViewsListFromExcelNLoadInPivotGrid(String absFilePath)
   ? Veda.FrontEnd.Results.UpdateExcelPresenter.Process(String initialDirectory, ResultsUpdateExcelMode resultsUpdateExcelMode)

**Comment by kanors-himanshu03** [comment]
This bug has been fixed in version 3.0.7.0.
