### ISSUE TITLE
"Implicit" TS Filtering no longer works

### ISSUE THREAD

**Issue by Antti-L** [kanors-emr/Veda2.0-Installation#36]
I just discovered that VEDA2 **v3.x** no longer correctly handles the "implicit" TS Filtering, using the syntax `<Year>-0`.  It worked still fine in VEDA2 versions **2.x**.  I did not yet test the explicit use of `TS_filter` column, but I assume that still works in v3.x.

**Question**:  Has the support for the "implicit" TS Filtering, using the syntax `<Year>-0` been dropped?  If so, that might mean a lot of checking and modifying of templates...

**Comment by akanudia** [comment]
Apologies for this hiccup Antti. Fortunately we trapped it in our final testing of version 307. Please take the production version that was released yesterday.

**Comment by Antti-L** [comment]
Thanks for the god news!
