### ISSUE TITLE
Not updating FILL tables if the content has not changed

### ISSUE THREAD

**Issue by olejandro** [kanors-emr/Veda2.0-Installation#37]
Currently `FILL*` tables are updated no matter whether the underlying data has changed or not. This introduces challenges in version controlling the files containing them, since they are flagged as modified even if their contents remains the same. 

Could Veda compare the original and the new tables and only change the file if the tables are different?

**Comment by Antti-L** [comment]
I agree that in principle this would be a nice thing to have, but it looks like it might impose some visible overhead. I would thus welcome this only if it is a true "Pareto improvement", i.e. no adverse impact on performance will be seen.

**Comment by akanudia** [comment]
Addressed in version 3.1.1.

We did not notice any performance degradation in our tests, but we made it a user option - in case one doesn't want to use this feature.
