### ISSUE TITLE
Sync logs in a text file

### ISSUE THREAD

**Issue by victor-guillot** [kanors-emr/Veda2.0-Installation#39]
Dear veda team, 
would it be possible to write the sync logs in a text file saved in the model folder ? That would ease the workflow with automatic test, text file diff and tracking the errors. I think veda1 was partially providing this kind of files.
Thanks
Victor

**Comment by RahulKanors** [comment]
We've approved your recommendation for this feature. It will be included in the next release.

**Comment by akanudia** [comment]
Addressed in version 3.1.1. They will be written to a new folder - SyncLogs.
