### ISSUE TITLE
Syncing: Excel error in v1-.248.1.2 Unable to cast COM object of type "Microsoft.Office.Interop.Excel.ApplicationClass"

### ISSUE THREAD

**Issue by energynumbers** [kanors-emr/Veda2.0-Installation#4]
![veda-error](https://user-images.githubusercontent.com/1759066/154981013-5210c563-1cf8-4662-8d30-6fb99e2fb9cb.png)

Getting this on model sync, windows 10, 21H2, OS 19044.1566

Excel: Microsoft 365 Apps for enterprise, v2201 build 14827.20198 Click-toRun, Current Channel.

**Comment by akanudia** [comment]
https://veda-documentation.readthedocs.io/en/latest/pages/Troubleshooting/Excel%20Exceptions.html#the-remote-procedure-call-failed-exception-from-hresult-0x800706be

does this help?

**Comment by energynumbers** [comment]
It didn't. But a full online repair of Microsoft 365 Apps for enterprise, did
