### ISSUE TITLE
Check (select) all tables in result viewer

### ISSUE THREAD

**Issue by BakytzhanSuleimenov** [kanors-emr/Veda2.0-Installation#40]
Hi there,

I found that in the last version (3.0.7.0) there is no option to choose all saved tables for export as it was previously (see picture). In the current version, it was substituted with a filter. As far as I know, there is no option to choose all tables using SHIFT or CTRL+A. So is it possible to bring back the "select all tables" feature?

Thanks a lot,
Bakytzhan

<img width="533" alt="image" src="https://github.com/kanors-emr/Veda2.0-Installation/assets/35721775/266841de-5464-492c-922d-139185224537">

**Comment by ravindersinghchauhan** [comment]
Dear Bakytzhan,

Thank you for pinpointing the issue. 
We've identified the bug, and this functionality will be included in the upcoming release.

**Comment by akanudia** [comment]
Addressed in version 3.1.1.
