### ISSUE TITLE
Show types of auxiliary commodities in RES View?

### ISSUE THREAD

**Issue by Antti-L** [kanors-emr/Veda2.0-Installation#41]
I wonder why the RES View shows the types of only part of the commodities in the topology.  As soon as one defines some of the commodities in the topology as auxiliaries, thereafter the commodity type is no longer shown, why so?  Example:

https://forum.kanors-emr.org/attachment.php?aid=1891

Could the commodity types be shown for all commodities in the topology?  Is there a technical problem hindering that?

**Comment by deepakgupta256** [comment]
The upcoming version of Veda will include this feature.

**Comment by kanors-himanshu03** [comment]
This change was implemented on June 7, 2024 and has been part of Veda since version 3.1.2.0.
