### ISSUE TITLE
Question about VDA_FLOP Deletions

### ISSUE THREAD

**Issue by Antti-L** [kanors-emr/Veda2.0-Installation#42]
I only just now realized that the deletion of any **VDA_FLOP**s defined for PCG members no longer causes any warnings.  And I also realize that defining VDA_FLOP for a PCG member no longer seems to works even in scenario files (it did work under VEDA-FE).  Again, no warning or error appears to be issued by VEDA2 about such parameters. I tried to check with Browse, and then double and triple check from the deletion logs (step1, step2), but found no trace of them anywhere...

Could the developers please just confirm whether these changes are intentional? I would think the very **silent deletion** might potentially cause some confusion. As to the removed support in scenario files, I am OK with that change (because ACT_FLO gives that functionality, if needed).

**Comment by akanudia** [comment]
Thanks for pointing this out @Antti-L . Our recent enhancements of the Sync log has had some unintended consequences. We also see spurious "no data was generated" messages in some cases. We will address this in the next update.

**Comment by Antti-L** [comment]
I can see that with the new release candidates for v3.1.4, there can be a huge amount of log entries generated for VDA_FLOPs that have been deleted (delete_log_step2).   Just in case someone might think that it was me who requested that, I would like to clarify that my request was to have log entries generated only when the VDA_FLOP might also have been expected to have some effect, i.e. when **VDA_FLOP<>1** has been defined for a member of the PCG, like it was under VEDA-FE, and which was quite useful.  

But now in the release candidate v3.1.4.8, all the VDA_FLOP=1 are also causing delete log entries, which is in my view not very useful. And I cannot see any easy way to **filter out the important cases** of VDA_FLOP<>1, if any, from the long list of deletions generated.  Under VEDA-FE I could immediately see a list of those important cases only.

**Comment by rohitkanors** [comment]
In version 4.0.0.0, delete log entries for significant cases where VDA_FLOP <> 1 will be reported. 
Cases where VDA_FLOP = 1 will not be reported.
