### ISSUE TITLE
Can't create new or view existing Table Master groups or select tables by filtering

### ISSUE THREAD

**Issue by tilseb** [kanors-emr/Veda2.0-Installation#44]
Dear VEDA Team,
In the Results tab I was trying to use an existing Table Master group, which was not displayed. Trying to redo the group doesn't work for me, as no tables are displayed to choose from.
Besides, when I want to select a subset of all saved tables using the filter function on the Saved tab of Results Tables, I need to select each table individually. The filter does not work on the select all tables box. Checking the select all box, selects all tables and disregards the filter.
I experienced these issues in VEDA version-3.1.1.0 and version-3.1.1.0
It would be nice if you could fix that, if those are general problems.
Thanks
Till

**Comment by ravindersinghchauhan** [comment]
Dear Till,

We’ll resolve this issue in the next version release. Thank you.

**Comment by RahulKanors** [comment]
Dear Till,

This has been addressed in the latest version [v3.2.1.0](https://github.com/kanors-emr/Veda2.0-Installation/releases/tag/v3.2.1.0).
