### ISSUE TITLE
Copy - paste from Item Detail  

### ISSUE THREAD

**Issue by panosev** [kanors-emr/Veda2.0-Installation#6]
In the RES View in items detail module, it would be nice if we can copy the items and paste them into the excel like in Veda_fe. For instance, when I look at a commodity in the RES View I would like to copy the names of the processes using or producing this commodity and paste these names in Excel etc. This it was possible in veda_fe but it seems it is not the case in veda2.0

**Comment by panosev** [comment]
If i select in veda_fe and then press CTRL+C then I can copy the selected items to Excel :-) It was very helpful feature 
I hope that the image shows a bit what I mean 

![image](https://user-images.githubusercontent.com/58793267/205686455-347aea44-b551-4b0e-b93c-ded61737264a.png)

**Comment by akanudia** [comment]
Apologies for losing track of this thread.

What if create a right-click menu on the list boxes in Items detail view and allow exporting all items as a list to clipboard? We can also have the option of including description and units information in the export.

**Comment by panosev** [comment]
Many thanks for this idea Amit :-)

**Comment by akanudia** [comment]
https://www.dropbox.com/s/x5uze7sxo3m2wd1/Veda2.0_localhost_2.10.1.12.7z?dl=0

Right-click on the boxes will give you the option to copy in this beta release. We can continue discussion on the Veda assistant thread. I will close this one.
